### ISSUE TITLE
Create Reading History Graph Component

### ISSUE THREAD

**Issue by jkufa** [ConfusedPolarBear/garden-sensor#19]
[Figma Sketch](https://www.figma.com/file/u0n8S6hm67qzUAWhMEZteD/Garden-IoT?node-id=0%3A1), 
[Chart.js](https://www.chartjs.org/)

This component needs to take in the following as input (dependent on button state):
* Sensor data for past Day **OR** sensor data for past week **OR** sensor data for past Month **OR** *all* sensor data

**Comment by ConfusedPolarBear** [comment]
This has been merged into the main branch, closing.
